### ISSUE TITLE
Issue with remote_posh,copy,upload commands 

### ISSUE THREAD

**Issue by kaleemshaik7867** [FortyNorthSecurity/WMImplant#23]
Hello,
Thank you for a great tool 
I am experimenting with some of the commands "remote_posh,copy,upload" on windows 7 system from windows 2008 R2 server with Local admin priv on windows 7 system.

I am getting following error when tried a script to run on remote system. I am getting following when I use remote_posh command and command prompt freezes 

Remote_posh

"Set-WmiInstance : Generic failure
At C:\Users\Administrator\Downloads\WMImplant-master\WMImplant-master\WMImplant.ps1:145 char:40
+                 $null = Set-WmiInstance <<<<  -Class Win32_Environment -Argument @{Name=$VarName;VariableValue=$PSCommand;UserName=$Username} -ComputerName $ComputerName
    + CategoryInfo          : InvalidOperation: (:) [Set-WmiInstance], ManagementException
    + FullyQualifiedErrorId : SetWMIManagementException,Microsoft.PowerShell.Commands.SetWmiInstance"

When I use Upload

Command >: upload
What system are you targeting? >: 172.16.117.180
What's the full path to the file you'd like to upload? >: C:\Users\Administrator\Desktop\test1.ps1
What is the full path to the location you would like the file uploaded to? >: C:\Windows\Temp\
Set-WmiInstance : Generic failure
At C:\Users\Administrator\Downloads\WMImplant-master\WMImplant-master\WMImplant.ps1:145 char:40
+                 $null = Set-WmiInstance <<<<  -Class Win32_Environment -Argument @{Name=$VarName;VariableValue=$PSCommand;UserName=$Username} -ComputerName $ComputerName
    + CategoryInfo          : InvalidOperation: (:) [Set-WmiInstance], ManagementException
    + FullyQualifiedErrorId : SetWMIManagementException,Microsoft.PowerShell.Commands.SetWmiInstance
![image](https://user-images.githubusercontent.com/7692857/43477405-2b1d5478-950c-11e8-8df0-36e6dbed0c4e.png)

Copy Command 

![image](https://user-images.githubusercontent.com/7692857/43477350-0349285a-950c-11e8-9594-5aab5644da8b.png)
But it did not copy the file

**Comment by kaleemshaik7867** [comment]
Can you please help me to understand and resolve the issue. I am not sure what I am doing wrong

**Comment by ChrisTruncer** [comment]
Are you by chance using this on a non-english language instance of Windows?

**Comment by kaleemshaik7867** [comment]
Hello Chris,

Thank you for the reply. I am using English version of Windows.

Regards,
Kaleem

**Comment by ChrisTruncer** [comment]
Can you provide any additional information? Is the file you're trying to copy, or upload, etc. containing non-english characters? That's the only known issue I know about with WMImplant. When I attempt to run the same commands in my lab, it is able to complete.

**Comment by kaleemshaik7867** [comment]
Hello Chris,

No it does not contain any non-english characters. At first I tried to upload a test file with content "test" in that 
[test.txt](https://github.com/FortyNorthSecurity/WMImplant/files/2258212/test.txt)

**Comment by ChrisTruncer** [comment]
Hi, I was able to successfully upload the file to the system I am targeting. Since that's the case, it leads me to think it is something with the system(s) you are testing with. Especially if using WMImplant locally on your own system, be sure to run with admin rights. When targeting a remote system, make sure you have permissions to write in the directory you are targeting.

If you can provide me with any additional information, I can look at it over the weekend or in the evening. Otherwise I unfortunately can't recreate this at the moment.

**Comment by kaleemshaik7867** [comment]
Hi Chris,

Thank you so much for your time and looking into it.  I will try the set up with other machine. If I still face any issues I will raise a new issue.

Closing this

**Comment by westlake2014** [comment]
> Hi Chris,
> 
> Thank you so much for your time and looking into it. I will try the set up with other machine. If I still face any issues I will raise a new issue.
> 
> Closing this

how to solve?
